### ISSUE TITLE
Empty Cyrillic Glyphs on Google Fonts

### ISSUE THREAD

**Issue by m4rc1e** [googlefonts/OswaldFont#10]
Some Cyrillic glyphs do not contain outlines 

![screen shot 2018-06-19 at 16 06 42](https://user-images.githubusercontent.com/7525512/41606148-ead516b4-73da-11e8-9a81-87550bee0cbf.png)

These fonts are being served

![screen shot 2018-06-19 at 16 07 01](https://user-images.githubusercontent.com/7525512/41606176-f3f65dca-73da-11e8-9112-3fde18539eb5.png)

It's pretty crazy but nobody has raised this issue yet.

Imo, this is a fairly serious issue. If a user types any of these characters, they don't get a fallback, they just get whitespace. I hope #9 fixes this. @NDISCOVER did you add outlines for these?

**Comment by NDISCOVER** [comment]
Yes I added all those glyphs

**Comment by m4rc1e** [comment]
Cool, I'll fix your regressions and we'll call it job done :-).
