### ISSUE TITLE
all styles are the same in firefox 67 mac os x 10.12

### ISSUE THREAD

**Issue by uhlik** [googlefonts/OswaldFont#15]
all styles are the same in firefox 67 mac os x 10.12, see screenshot of https://fonts.google.com/specimen/Oswald from Firefox 67. also when used on website the issue persists, all font styles are the same. in Chrome 75 works as expected. Firefox worked i'd say 2 months ago..

![](http://pasteall.org/pic/show.php?id=3956a2f40421aed9d300fb795b4a2fce "")

**Comment by m4rc1e** [comment]
Looks fine on my Mac Firefox 67

<img width="1392" alt="Screenshot 2019-06-20 at 15 06 12" src="https://user-images.githubusercontent.com/7525512/59855534-0cfaeb80-936d-11e9-8a28-02cba7539faf.png">

Have you got the font installed locally?

**Comment by uhlik** [comment]
no, i have not, checked files and font book. maybe relatively old OS is the problem, i run 10.12, i checked other machine with also 10.12 and problem is still there..

**Comment by uhlik** [comment]
hi, just to inform you, ff 69.0.3 is working again
