### ISSUE TITLE
line spacing is too big

### ISSUE THREAD

**Issue by paulz** [googlefonts/OswaldFont#28]
<img width="103" alt="image" src="https://user-images.githubusercontent.com/59230/193146458-da502e10-6001-4c10-83aa-aa109215dd85.png">

even with line spacing 0 we see big space between lines when we use Oswald Regular

**Comment by paulz** [comment]
adjusting these custom font parameters in https://glyphsapp.com
<img width="568" alt="image" src="https://user-images.githubusercontent.com/59230/193191838-d9e447b5-1b3c-4ad8-b42e-377f6236b73c.png">
we are able to reduce line spacing:

<img width="1873" alt="Pasted Image at 2022_09_29_21_29 pm" src="https://user-images.githubusercontent.com/59230/193192069-db16e20c-44e5-450d-973b-e9c3f0de455d.png">

**Comment by paulz** [comment]
Here is original font custom parameters:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/59230/193192245-aff1b234-cf46-41e1-8f79-c65d86e17616.png">

Now we need to bisect to see which of the parameters actually affected line spacing

**Comment by paulz** [comment]
one of the following properties inside `.glyph` file
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
  <dict>
    <key>customParameters</key>
    <array>
      <dict>
        <key>name</key>
        <string>typoAscender</string>
        <key>value</key>
        <string>600</string>
      </dict>
      <dict>
        <key>name</key>
        <string>typoDescender</string>
        <key>value</key>
        <string>-100</string>
      </dict>
      <dict>
        <key>name</key>
        <string>typoLineGap</string>
        <key>value</key>
        <string>0</string>
      </dict>
      <dict>
        <key>name</key>
        <string>winAscent</string>
        <key>value</key>
        <string>800</string>
      </dict>
      <dict>
        <key>name</key>
        <string>winDescent</string>
        <key>value</key>
        <string>200</string>
      </dict>
      <dict>
        <key>name</key>
        <string>hheaAscender</string>
        <key>value</key>
        <string>700</string>
      </dict>
      <dict>
        <key>name</key>
        <string>hheaDescender</string>
        <key>value</key>
        <string>-100</string>
      </dict>
      <dict>
        <key>name</key>
        <string>strikeoutPosition</string>
        <key>value</key>
        <string>347</string>
      </dict>
      <dict>
        <key>name</key>
        <string>strikeoutSize</string>
        <key>value</key>
        <string>50</string>
      </dict>
    </array>
    <key>id</key>
    <string>m01</string>
    <key>metricValues</key>
    <array>
      <dict>
        <key>pos</key>
        <string>593</string>
      </dict>
      <dict>
        <key>pos</key>
        <string>610</string>
      </dict>
      <dict>
        <key>pos</key>
        <string>578</string>
      </dict>
      <dict/>
      <dict>
        <key>pos</key>
        <string>-100</string>
      </dict>
      <dict/>
    </array>
    <key>name</key>
    <string>Regular</string>
  </dict>
</array>
</plist>

```

**Comment by paulz** [comment]
Here is macOS Times New Roman letter C showing vertical metrics:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/59230/193201228-705b99f3-9ca3-4376-81a8-d43359ad897d.png">

And here is the the Oswald:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/59230/193201293-6532d314-ddc1-49b5-8e23-0abfd221c646.png">

we can see winDescender has extra space

**Comment by m4rc1e** [comment]
We can't change the linespacing because the family has been released for a long time. If we change it, documents will reflow incorrectly.

**Comment by paulz** [comment]
thank you @m4rc1e 

we found good metrics for the font that fix line spacing, our designer is happy with these values:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/59230/193327457-43850582-f658-4223-960a-b79c2a304964.png">

**Comment by paulz** [comment]
new line spacing on the right compared with existing on the left:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/59230/193327739-b3397d67-7645-4775-911e-c9d153a29260.png">

**Comment by m4rc1e** [comment]
Any reason why you can't change the linespacing using leading or css line-height?

**Comment by paulz** [comment]
Thank you Marc,

We are using this font on iOS and macOS directly without CSS.

Here is what we tried:
1. set leading to `.tight` instead of `.standard`
2. setting line spacing to 0

but line spacing was still too big as shown on the picture: https://github.com/googlefonts/OswaldFont/issues/28#issue-1391531802
