### ISSUE TITLE
Add 0x02bb (ʻ)

### ISSUE THREAD

**Issue by davelab6** [googlefonts/OswaldFont#8]
I'd like to request just one more character to make all languages currently supported 100%

| Language (code) | Coverage | %Coverage | Missing Characters |
| ---- | ---- | ---- | ---- |
| Uzbek (uz) | 86/87 | 98 | \u02bb (ʻ) |

**Comment by kalapi** [comment]
@davelab6 will add this in the next couple of days.

**Comment by davelab6** [comment]
Any updates? If you are busy, @ndiscover could take care of this

**Comment by kalapi** [comment]
@davelab6 I think it would be better if @NDISCOVER incorporated the character because I see that the Cyrillic glyphs are a WIP. If he has un-commited changes, my pull request will become complicated to merge.

**Comment by davelab6** [comment]
Sounds good

**Comment by NDISCOVER** [comment]
We will add it to ours before comiting the rest of the Cyrillic.

**Comment by NDISCOVER** [comment]
Done

NDISCOVER
Digital Typography
